# Generated by Django 6.0.8 on 2026-08-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='stacks/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('git_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('hours_spent', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ai_type', models.CharField(choices=[('full_ai', 'Full AI with understanding'), ('half_ai', 'Half AI / Half self'), ('no_ai', 'Fully self-made')], max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stacks', models.ManyToManyField(blank=True, to='projects.techstack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
