# Generated by Django 6.0.8 on 2026-08-18 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description_de_project_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='stacks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
