# Generated by Django 6.0.8 on 2026-08-27 16:30

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_techstack_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='stacks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdfs/'),
        ),
    ]
